#!/bin/bash

start_server() {
  javac -cp "./bin:$(mvn dependency:build-classpath | grep -v '^\[')" -d ./bin src/main/java/com/blitzhetz/server/*.java
  java -cp "./bin:$(mvn dependency:build-classpath | grep -v '^\[')" com.blitzhetz.server.ChattyServer
}

start_client() {
  javac -cp "./bin:$(mvn dependency:build-classpath | grep -v '^\[')" -d ./bin src/main/java/com/blitzhetz/client/*.java
  java -cp "./bin:$(mvn dependency:build-classpath | grep -v '^\[')" com.blitzhetz.client.ChattyClient
}

if [ "$1" == "server" ]; then
  start_server
elif [ "$1" == "client" ]; then
  start_client
else
  echo "Usage: $0 (server|client)"
  exit 1
fi
